### ISSUE TITLE
FS19 status

### ISSUE THREAD

**Issue by Sythos** [Mogli12/AIVehicleExtension#130]
any plan to port to FS19? :D

**Comment by cabmac** [comment]
i would say.. no lua-doc, no  plan....

**Comment by omegaMV6** [comment]
Hallo Mogli,

ich weiß, Du (und Deine Kollegen?) arbeitest zur Zeit hart an KeyboardSteer. Ich wollte nur mal höflich nachfragen, ob Du jetzt, wo die Script-Doku veröffentlicht wurde, eine Chance siehst die AiVE für den FS19 zu konvertieren. Leider ist der Giants-Helfer immer noch "dumm wie ein Meter Feldweg", so daß man ihn ständig im Auge behalten muss!
Vielleicht hast Du irgendwann mal eine ruhige Minute, um für uns Fans Deines Mods hier einen Einzeiler zu schreiben.

Ein Frohes Fest wünscht  
omegaMV6

**Comment by Mogli12** [comment]
Hi,

I checked the LUADOC even more. But there are so many gaps. Many old methods like aiTurnOn, aiTurnOff or not available anymore. But there is a method raiseAIEvent. It is not documented. It seems that it should do something.

Overall this is too frustrating. So I decided not to convert AIVE.

Regards,
Stefan

**Comment by omegaMV6** [comment]
Hi Stefan,

das sind keine schönen Nachrichten. Manchmal hat man den Eindruck, Giants hat vergessen wer das Spiel so erfolgreich gemacht hat. 
Hat man nicht euch Scripter, Modder und Mapper als quasi unverzichtbaren Baustein des Games bezeichnet? Schade, dass man euch nun so im Regen stehen lässt mit der Script-Doku. 
Ich kann nur hoffen, dass Dir vielleicht doch noch eine Möglichkeit einfällt, die AIVE für den LS19 zu bringen. 
Aber jetzt genieße erst mal die Feiertage.
Ich wünsche Dir und Deiner Familie frohe Weihnachten und einen guten Rutsch. 

LG
omegaMV6 
(Peter)

P.S. entschuldige bitte das ich auf deutsch schreibe. Hab es schnell am Handy getippt. Kann es aber heute Abend nochmal mit meinem Schulenglisch schreiben. Dauert halt ein bisschen länger ;)
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 19.12.18, 14:17, Stefan Biedenstein <notifications@github.com> schrieb:
Hi,
I checked the LUADOC even more. But there are so many gaps. Many old methods like aiTurnOn, aiTurnOff or not available anymore. But there is a method raiseAIEvent. It is not documented. It seems that it should do something.
Overall this is too frustrating. So I decided not to convert AIVE.
Regards,
Stefan

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Mogli12/AIVehicleExtension","title":"Mogli12/AIVehicleExtension","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Mogli12/AIVehicleExtension"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Mogli12 in #130: Hi,\r\n\r\nI checked the LUADOC even more. But there are so many gaps. Many old methods like aiTurnOn, aiTurnOff or not available anymore. But there is a method raiseAIEvent. It is not documented. It seems that it should do something.\r\n\r\nOverall this is too frustrating. So I decided not to convert AIVE.\r\n\r\nRegards,\r\nStefan"}],"action":{"name":"View Issue","url":"https://github.com/Mogli12/AIVehicleExtension/issues/130#issuecomment-448593704"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Mogli12/AIVehicleExtension/issues/130#issuecomment-448593704",
"url": "https://github.com/Mogli12/AIVehicleExtension/issues/130#issuecomment-448593704",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by theSeb1979** [comment]
Sad news. This game isn’t playable for me without this mod.
