### ISSUE TITLE
Distance between combines

### ISSUE THREAD

**Issue by Stepa27** [Mogli12/AIVehicleExtension#48]
Hello Mogli

I have noticed that combines do not keep safe distance between themselves. For example, if combine A stop, combine B will come few meters behind and slightly turn left. 

In FS15 autocombine mod there was option to set distance from vehicle in front of you. That allowed us to use more combines on the same field. Are you able to add this option?

**Comment by Mogli12** [comment]
Maybe...

**Comment by Stepa27** [comment]
Cool.

**Comment by 3lronMcBong** [comment]
das wäre echt super :-)

**Comment by Stepa27** [comment]
Still not working
http://i66.tinypic.com/10xtusl.jpg
http://i67.tinypic.com/2vtsfbn.jpg

**Comment by Mogli12** [comment]
Hi,

You need to have enough distance between 1st and 2nd vehicle before you start the AI in the 2nd vehicle.

Regards, Stefan

**Comment by Mogli12** [comment]
Does it work with the most recent beta?

**Comment by Stepa27** [comment]
With beta10 second combine refuse to start harvesting, simply standing in one place. Tested with 3 combines.

**Comment by Mogli12** [comment]
Hi,

I do not know what you are doing. I tested it with two NH CR1.90. As I already wrote before: Please keep some distance between the combines **before** you start them. And the collision check only works in circular mode.

Regards, Stefan

**Comment by Stepa27** [comment]
Dude, I don't know what are you doing.. When first combine get full tank and stop, it wont start to harvest again. Now i use your 0406 version, its good that i have backup :)

**Comment by Mogli12** [comment]
Ok, I will disavle the collision check. I do not like such endless issues without a clear step-by-step problem description.

**Comment by Echelon2k** [comment]
I know this issue has been closed already but i think what the Stepha is referring to is when the leading combne is stopping because its tank is full, the following combines basic logic takes over and aims it at the nearest corner of non-harvested grain. Which is right infront of the leading combine so it ends up in an angle. This issue fixes itself though when the leading combine gets rolling again. At least it does with the gearbox mod or any other that mod that prevents near instant speed changes installed as the leading combine gains distance again faster than the folowing can keep up.

**Comment by Mogli12** [comment]
I currently trying to finalize version 1.0. If a feature is not working or if it is too complicated to understand I will disable it.
